# Generated by Django 3.0.2 on 2020-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
    ]
