# Generated by Django 3.0.2 on 2020-10-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20201021_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
